package com.jojoldu.book.springboot.fifa;

public class ApiKey {
    public static String API_KEY= "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50X2lkIjoiMTYxMTI0ODg1NCIsImF1dGhfaWQiOiIyIiwidG9rZW5fdHlwZSI6IkFjY2Vzc1Rva2VuIiwic2VydmljZV9pZCI6IjQzMDAxMTQ4MSIsIlgtQXBwLVJhdGUtTGltaXQiOiI1MDA6MTAiLCJuYmYiOjE2MzM4NzEwODAsImV4cCI6MTY0OTQyMzA4MCwiaWF0IjoxNjMzODcxMDgwfQ.w0pXAAixKOhqqpJKybmBsXPvveTGSo7ZxnJX5NKsBzk";
}
